---
- name: Install python3, docker, docker-compose
  hosts: docker_server
  become: yes
  gather_facts: False
  tasks:
    - name: Install python3 and docker
      vars: 
        ansible_python_interpreter: /usr/bin/python
      yum:
        name: 
          - python3
          - docker
          - pip
        update_cache: yes
        state: present
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-Linux-{{lookup('pipe','uname -m')}}
        dest: /usr/local/bin/docker-compose.yaml
        mode: +x
    - name: Start docker daemon
      systemd:
        name: docker
        state: started
    - name: Install docker python module
      pip: 
        name: 
          - docker
          - docker-compose



- name: Add ec2-user to docker group
  hosts: docker_server
  become: yes
  tasks:
    - name: Add ec2-user to docker group
      user:
        name: ec2-user
        groups: docker
        append: yes
    - name: Reconnect to server session
      meta: reset_connection



- name: Start docker container
  hosts: docker_server
  vars_prompt:
    - name: docker_password
      prompt: Enter password for docker registry
  tasks:
    - name: Copy docker compose
      copy:
        src: /home/abhishek/Desktop/misc/DevOps/Ansible/docker-compose.yaml
        dest: /home/ec2-user/docker-compose.yaml
    - name: Docker login
      docker_login:
        registry_url: https://index.docker.io/v1/
        username: bobbyy16
        password: "{{docker_password}}"
    - name: Start container from compose
      docker_compose:
        project_src: /home/ec2-user
        state: present #present means up or absent means down

 

# - name: Test docker pull
#   hosts: docker_server
#   tasks:
#     - name: pull redis
#       docker_image:
#         name: redis
#         source: pull

# Its integrated with Terraform so We can start this with terraform to
 