---
- name: configure nginx web server
  hosts: webserver
  tasks: 
  - name: install nginx server
    apt:
      name: nginx #nginx=1.18.0-0ubuntu1
      state: latest #present #absent to delete
  - name: start nginx server
    service:
      name: nginx
      state: started #stoppped